spring:
  datasource:
    url: jdbc:mysql://192.168.184.100:3306/mall_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: mqw12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-merchant # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.184.100:8848
      discovery:
        username: nacos
        password: nacos
mybatis-plus:
  type-aliases-package: com.mall_wml.merchant.domain.po
  mapper-locations: classpath:mapper/*.xml


# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /merchant/v3/api-docs  #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs: #分组配置,可配置多个分组
    - group: 'merchant-api'
      paths-to-match: '/**'
      packages-to-scan: com.mall_wml.merchant
server:
  port: 9093
